// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartBulb.Data;

namespace SmartBulb.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SmartBulb.Data.Models.BulbState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Brightness")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorTemp")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Hue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Saturation")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TransitionTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BulbState");
                });

            modelBuilder.Entity("SmartBulb.Data.Models.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EndStateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartHour")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartMinute")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StartStateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EndStateId");

                    b.HasIndex("StartStateId");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("SmartBulb.Data.Models.SetStateTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ScriptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaitTime")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScriptId");

                    b.HasIndex("StateId");

                    b.ToTable("SetStateTask");
                });

            modelBuilder.Entity("SmartBulb.Data.Models.Script", b =>
                {
                    b.HasOne("SmartBulb.Data.Models.SetStateTask", "EndState")
                        .WithMany()
                        .HasForeignKey("EndStateId");

                    b.HasOne("SmartBulb.Data.Models.SetStateTask", "StartState")
                        .WithMany()
                        .HasForeignKey("StartStateId");
                });

            modelBuilder.Entity("SmartBulb.Data.Models.SetStateTask", b =>
                {
                    b.HasOne("SmartBulb.Data.Models.Script", null)
                        .WithMany("RepeatedTasks")
                        .HasForeignKey("ScriptId");

                    b.HasOne("SmartBulb.Data.Models.BulbState", "State")
                        .WithMany()
                        .HasForeignKey("StateId");
                });
#pragma warning restore 612, 618
        }
    }
}
